feat: added exponential back-off to handle failed attempts to establish connection to the server
mendersoftware/mender-connect pull request #118
Opened 2023-11-28 08:50 UTC by danielskinstad

Exponentially backs off until max (5 minutes) is reached. It will then keep retrying every 5 minutes.

Changelog: Title

Ticket: MEN-5782

2023-11-30 08:38 UTC, alfrunes requested changes
Great work getting your hands dirty with some Go programming, starting with `mender-connect` is pretty brave :smile_cat:
First off, when it comes to the exponential back-off, I believe there should only be exponential back-off when trying to establish the websocket connection as this is the only path that directly interacts with the server. Your implementation is adding delay one step further out - interacting with the `mender` client on the device (using the dbus api). So I would first move the logic to the `connectionmanager` package.
Second, when it comes to the algorithm itself, it seems a bit arbitrary. Imagine millions of devices connected to a server and then a transient error causes all devices to loose connection. Now, all clients will in unison try to reconnect to the server which in turn significantly increase the burden for the server to recover. So I suggest we add a little bit of randomness delay on top of the exponential backoff, as well as increase the maximum interval. Ideally I would prefer if there instead were a cutoff interval where the algorithm changes to increase the interval linearly. For example, do exponential random backoff up to 1 hour. Then, for each attempt, increase the interval by 1-2 minutes (randomly chosen).

2023-12-07 13:36 UTC, alfrunes requested changes
The back-off needs to happen before the call to `connection.NewConnection`.
I know we also talked about the removal of retries, but now I'm not sure. I don't know the intricacies about the dbus API, I'd like to get some input from @merlin-northern or @lluiscampos about this.

2023-12-07 13:36 UTC, alfrunes commented on connectionmanager/connectionmanager.go
> +	c, err = connection.NewConnection(u, token, writeWait, maxMessageSize, DefaultPingWait)
The back-off should protect `connection.NewConnection`. For example:
```go
	if err := a.Backoff(ctx); err != nil {
		return err
	}
	c, err = connection.NewConnection(u, token, writeWait, maxMessageSize, DefaultPingWait)
```
Where `a.WaitForBackoff` would look something like:
```go
func (a *expBackoff) Backoff(ctx context.Context, proto ws.ProtoType) error {
	a.attempts++
	if a.attempts <= 1 {
		return nil
	}
	intrval := a.GetExponentialBackoffTime()
	select {
	case <-time.After(a.GetExponentialBackoffTime()):
	case <-cancelReconnectChan[proto]:
		return context.Canceled
	case <-ctx.Done():
		return ctx.Err()
	}
	return nil
}
```

2023-12-07 13:36 UTC, alfrunes commented on connectionmanager/connectionmanager.go
>  			return err
Waiting to return the already available error is a waste of time. The waiting should happen before the call to establish the connection.

2023-12-07 13:36 UTC, alfrunes commented on connectionmanager/exponentialbackoff.go
> +	nextInterval = interval << (a.attempts / perIntervalAttempts)
The `perIntervalAttempts` seems a bit arbitrary. I know this comes from the mender client, but I do not understand the purpose of such a mechanism.

2023-12-18 07:39 UTC, merlin-northern commented
> The back-off needs to happen before the call to `connection.NewConnection`. I know we also talked about the removal of retries, but now I'm not sure. I don't know the intricacies about the dbus API, I'd like to get some input from @merlin-northern or @lluiscampos about this.

sorry I am a bit late for the party. @alfrunes what shall I do? do you want me to give a full review? the dbus API: without reading the current code, and as far as I remember there is a separete go routine which monitors for the dbus events. in general what you have eto take into account with the back off is the fac that you can loose authorization at any given moment. let me know how I can be os assistance.

2024-01-30 11:42 UTC, lluiscampos requested changes
> The back-off needs to happen before the call to `connection.NewConnection`. 

I agree

> I know we also talked about the removal of retries, but now I'm not sure. I don't know the intricacies about the dbus API, I'd like to get some input from @merlin-northern or @lluiscampos about this.

As far as I can see, this should be fine. From the `dbusEventLoop` the ongoing (re)connection is cancelled* when the server url or the token change, so it will exit back to the main context in `eventLoop` and then start the new connection attempt.

(*) It is not very intuitive, but in `processJwtTokenStateChange` we call `connectionmanager.Close` which in turn will send the cancel through `cancelReconnectChan[proto]`.

Now, one could argue that this was the case before and that `MaxReconnectAttempts` did not have any reason to exist. So I might be missing something :eyes: Am I?

If you @alfrunes nor @merlin-northern aren't confident with my theory, then I suggest that we re-introduce `MaxReconnectAttempts` and modify the backoff algorithm of this PR to stop after such many attempts, this way it will still behave as it used to wrt eventually going back to `eventLoop` and starting all over (re)connection.

2024-01-30 11:42 UTC, lluiscampos commented on connectionmanager/exponentialbackoff.go
> +	// Retry time does not increaseb beyond maxBackoff
```suggestion
	// Retry time does not increase beyond maxBackoff
```

2024-01-30 13:42 UTC, alfrunes commented
> If you @alfrunes nor @merlin-northern aren't confident with my theory, then I suggest that we re-introduce `MaxReconnectAttempts` and modify the backoff algorithm of this PR to stop after such many attempts, this way it will still behave as it used to wrt eventually going back to `eventLoop` and starting all over (re)connection.

To be honest, I'm not very familiar with the connection management and dbus stuff, but I gave it a shot creating the simplest wrapper around the websocket interface that I could come up with: https://github.com/mendersoftware/mender-connect/pull/133

2024-02-03 19:14 UTC, merlin-northern commented on connectionmanager/connectionmanager.go
>  func connect(
@alfrunes  @danielskinstad @lluiscampos I leav the details of the review for you. what I verified is: this (the `connect` function) is the correct place to introduce the backoff -- the reconnect mechanism via events is independent (mostly) from the dbus events.

2024-02-16 08:59 UTC, lluiscampos approved these changes
I think this is coming together pretty nicely now! I commented on few things, but overall looks good so I am pre-approving it.

With regards to your Git history,
* The two commits in this PR should really be one. We are not very consistent in the team, but the principle should be that each commit is "buildable" - meaning if you change function you should fix the tests in the same commit.
* The title for your commits are very long. Please have a look at [this source](https://thoughtbot.com/blog/5-useful-tips-for-a-better-commit-message) (and, specifically, the vim configuration :wink: ). This is one of your first PRs and I know you have improved the messaging since, but having vim highlighting the syntax will help you write better commit messages when amending too :smiley:

2024-02-16 08:59 UTC, lluiscampos commented on connectionmanager/exponentialbackoff.go
> +		}
This is not necessary as it will `return nil` anyway on the next statement

2024-02-16 08:59 UTC, lluiscampos commented on connectionmanager/exponentialbackoff.go
> +	log.Errorf("connectionmanager backoff: retrying in %s", a.interval)
This is not an error, I suggest using an `Info` log entry here.

2024-02-20 12:44 UTC, danielskinstad commented
@mender-test-bot start pipeline

2024-02-26 13:30 UTC, danielskinstad commented
@mender-test-bot start pipeline --pr meta-mender/2080

2024-02-28 09:11 UTC, alfrunes reviewed
*Review dismissed

2024-02-28 09:12 UTC, alfrunes approved these changes
Unblocking my blocking review.

2024-02-28 12:51 UTC, merlin-northern commented on connectionmanager/connectionmanager.go
>  func connect(
I have total and uttermost trust in my team mates. proceed.

2024-02-29 10:56 UTC, merged