chore: removed the text "mender-connect version" from --version outpu…
mendersoftware/mender-connect pull request #128
Opened 2024-01-18 20:31 UTC by danielskinstad

…t to be consistent

Changelog: --version no longer outputs the text "mender-connect version".

Ticket: MEN-6965

2024-01-19 07:15 UTC, lluiscampos requested changes
The code looks good.

However you are doing two things in this commit: to remove the `version` command and to modify the output for the `--version` flag. This could have very well been two separate commits.

For the first part, we are technically speaking removing a command (the `version` command) and it is a breaking change, which will require a major version bump.

Either:
* Drop the removal of `version` command.
* Separate the commits and mark the removal of `version` command as a [breaking change](https://github.com/mendersoftware/mendertesting/blob/master/commitlint/grammar.md#notes).
    * @oleorhagen I think it is an overkill, but I'd rather be technically correct wrt semantic version that run into trouble in the future because someone out there did use this command... What do you think?

2024-01-19 08:58 UTC, oleorhagen commented
> The code looks good.
> 
> However you are doing two things in this commit: to remove the `version` command and to modify the output for the `--version` flag. This could have very well been two separate commits.
> 
> For the first part, we are technically speaking removing a command (the `version` command) and it is a breaking change, which will require a major version bump.
> 
> Either:
> 
>     * Drop the removal of `version` command.
> 
>     * Separate the commits and mark the removal of `version` command as a [breaking change](https://github.com/mendersoftware/mendertesting/blob/master/commitlint/grammar.md#notes).
>       
>       * @oleorhagen I think it is an overkill, but I'd rather be technically correct wrt semantic version that run into trouble in the future because someone out there did use this command... What do you think?

Yes, I agree. I mean, this could've even broken some of our stuff

2024-01-19 08:59 UTC, oleorhagen commented
So, yeah. I mean. I vote for keeping the command. That is option 1.

2024-01-19 10:39 UTC, lluiscampos approved these changes

2024-01-19 12:03 UTC, danielskinstad commented
@mender-test-bot start pipeline

2024-01-22 07:38 UTC, lluiscampos commented
The failing test is a known and unrelated issue. Merging

2024-01-22 07:38 UTC, merged